export const LOGIN_ROUTE = '/login'
export const SIGNUP_ROUTE = '/signup'
export const HOME_ROUTE = '/home'
export const CARD_ROUTE = '/card'
export const FAVORITES_ROUTE = '/favorites'
export const HISTORY_ROUTE = '/history'
export const MAIN_ROUTE = '/'
export const SEARCH_ROUTE = '/search'
