export const LOGIN_ROUTE  = '/login'
export const SIGNUP_ROUTE = '/signup'
export const HOME_ROUTE = '/home'
export const ELEMENT_ROUTE = '/element'
export const FAVORITES_ROUTE = '/favorites'
export const HISTORY_ROUTE = '/history'
export const LOGOUT_ROUTE = '/logout'
export const MAIN_ROUTE = '/'